FROM python:latest

# Install requirements
COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

# Copy the application
COPY . /app

# Set the working directory
WORKDIR /app

# Expose the port
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]